### ISSUE TITLE
To-do lists

### ISSUE THREAD

**Issue by rickselby** [rickselby/acsr-server#12]
### Dashboard
- [x] Server status
- [x] Races Summary (full list, status, grid / results)
- [x] Save results JSONs
- [x] Download links to JSONs
- [ ] AJAXify the dashboard?

### Users
- [x] Driver numbers (skin names) - admin only?
- [ ] ~~Is user in general chat function~~ _not possible_

### Before first test

- [x] Announce heat lineups in announcements
- [x] Check grids with 'empty' slots in them work
- [x] Show users' discord & steam names if they're not on the server yet

**Comment by rickselby** [comment]
Before first test

- [ ] Announce heat lineups in announcements

**Comment by rickselby** [comment]
Things that broke:

- [x] progression of sessions (reload race / event?)
- [x] discord api overloaded
- [x] creating directory for jsons

**Comment by rickselby** [comment]
both servers in the UK boo :(

**Comment by rickselby** [comment]
fastest lap sorting the wrong way?

**Comment by rickselby** [comment]
finals laps incorrect

**Comment by rickselby** [comment]
https://github.com/hammerandchisel/discord-api-docs/issues/179

https://github.com/hammerandchisel/discord-api-docs/issues/190

**Comment by rickselby** [comment]
Remove "heat x is up" messages when heat is complete?

**Comment by rickselby** [comment]
Delete channel not working...

**Comment by rickselby** [comment]
skin identifier not appearing in entry lists

**Comment by rickselby** [comment]
start next session doesn't do anything with moving people up within finals
basically fix the bloody progression stuff (discord delete channel)
